### ISSUE TITLE
sha1 algorithm only worked

### ISSUE THREAD

**Issue by MohamedFaroukAbdelazeem** [xarenard/simpleotp#5]
fix this function 
add const algorithm to options to create the same validate token

    Hotp.prototype.validate = function (data) {
        const expectedToken = data.token;
        const counter = data.counter;
        const secret = data.secret;
        const window = data.window;
        const num_digits = this.options.num_digits;
        **const algorithm = data.algorithm;**

	let isValid = false;
	let window_frame = counter + (window || 0);

	let i = counter;
	while(i <= window_frame && !isValid){
		let token = this.createToken({num_digits: num_digits,counter:i,secret: secret,encoding: data.encoding ,**algorithm: data.algorithm**});
		if (token.toString() === expectedToken) {
			isValid = true;
		}
		i++;
	}
	return isValid;
};

**Comment by xarenard** [comment]
Hi Mohamed,

Thanks for your feedback. It is true that, to be consistent, sha256 should be added to validate method or be completely removed from the method createtoken as the algorithm can be generated from the constructor (new Hotp({algorithm:sha256})
I will review your PR and come back to you

Cheers
